Sonal_DropDown/Models/CascadeDDL.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;

namespace Sonal_DropDown.Models
{
    public class CascadeDDL
    {
        private DbConfig db = new DbConfig();
        public List<Cascading> GetCountries()
        {
            SqlCommand cmd = new SqlCommand("SP_GetCountry", db.sql);
            cmd.CommandType = CommandType.StoredProcedure;

            //open coonection if it's closed
            if (db.sql.State == ConnectionState.Closed)
                db.sql.Open();

            var result = cmd.ExecuteReader();
            List<Cascading> ls = new List<Cascading>();
            while(result.Read())
            {
                Cascading obj = new Cascading();
                obj.Id =(int) result[0];
                obj.Name =result[1].ToString();
                ls.Add(obj);
            }
            db.sql.Close();
            return ls;
        }

        public List<Cascading> GetStates(int Id)
        {
            SqlCommand cmd = new SqlCommand("SP_GetState", db.sql);
            cmd.CommandType = CommandType.StoredProcedure;

            SqlParameter sqlParameter = new SqlParameter();
            sqlParameter.ParameterName = "@CountryId";
            sqlParameter.Value = Id;
            sqlParameter.DbType = DbType.Int32;
            cmd.Parameters.Add(sqlParameter);

            //open coonection if it's closed
            if (db.sql.State == ConnectionState.Closed)
                db.sql.Open();

            SqlDataReader result = cmd.ExecuteReader();

            List<Cascading> statelist = new List<Cascading>();
            while (result.Read())
            {
                Cascading obj = new Cascading();
                obj.Id = (int)result[0];
                obj.Name = result[1].ToString();
                statelist.Add(obj);
            }
            db.sql.Close();
            return statelist;
        }

        public List<Cascading> GetCities(int Id)
        {
            SqlCommand cmd = new SqlCommand("SP_GetCity", db.sql);
            cmd.CommandType = CommandType.StoredProcedure;

            SqlParameter sqlParameter = new SqlParameter();
            sqlParameter.ParameterName = "@StateId";
            sqlParameter.Value = Id;
            sqlParameter.DbType = DbType.Int32;
            cmd.Parameters.Add(sqlParameter);
            //open coonection if it's closed
            if (db.sql.State == ConnectionState.Closed)
                db.sql.Open();

            SqlDataReader result = cmd.ExecuteReader();
            List<Cascading> cityList = new List<Cascading>();
            while (result.Read())
            {
                Cascading obj = new Cascading();
                obj.Id = (int)result[0];
                obj.Name = result[1].ToString();
                cityList.Add(obj);
            }
            db.sql.Close();
            return cityList;
        }

    }
}

Sonal_DropDown/Models/DbConfig.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;

namespace Sonal_DropDown.Models
{
    public class DbConfig
    {
        public SqlConnection sql { get; set; }

        public DbConfig()
        {
            string Cnn = ConfigurationManager.ConnectionStrings["conn"].ConnectionString;
            sql = new SqlConnection(Cnn);
        }
    }
}

Sonal_DropDown/Controllers/CascadeController.cs
using Sonal_DropDown.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sonal_DropDown.Controllers
{
    public class CascadeController : Controller
    {
        CascadeDDL dB = new CascadeDDL();
        public ActionResult Index()
        {

            return View();
        }

        public JsonResult GetCountry()
        {
            var countries = dB.GetCountries();
            return Json(countries, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetState(int id)
        {
            var states = dB.GetStates(id);
            return Json(states, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCity(int id)
        {
            var cities = dB.GetCities(id);
            return Json(cities, JsonRequestBehavior.AllowGet);
        }


    }
}

Sonal_DropDown/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sonal_DropDown.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Sonal_DropDown/Views/Cascade/Index.cshtml
@model IEnumerable<Sonal_DropDown.Models.Cascading>
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-6 offset-3 ">
        <div>
            <div class="form-group">
                <label>Select Country</label>
                <select class="form-control" id="ddlcountry">
                    <option>Select</option>
                </select>
            </div>

            <div class="form-group">
                <label>Select State</label>
                <select class="form-control" id="ddlstate">
                    <option>Select</option>
                </select>
            </div>

            <div class="form-group">
                <label>Select City</label>
                <select class="form-control" id="ddlcity">
                    <option>Select</option>
                </select>
            </div>

        </div>
    </div>

</div>


<script type="text/javascript">

    $(document).ready(function () {

        loadcountry()

        $("#ddlcountry").change(function () {
            loadstate();
        })

        $("#ddlstate").change(function () {
            loadcity();
        })


    })

    function loadcountry() {

        $.get('@Url.Action("GetCountry", "Cascade")', function (response) {

            $.each(response, function(i,e) {
                $("#ddlcountry").append("<option value="+e.Id+">"+e.Name+"</option>")
            })
        })
    }

    function loadstate() {

        var cid = $("#ddlcountry").val()
        $.get('@Url.Action("GetState", "Cascade")', { id: cid }, function (response) {

            $("#ddlstate").empty()
            $("#ddlstate").append("<option>Select</option>")

            $.each(response, function(i,e) {
                $("#ddlstate").append("<option value="+e.Id+">"+e.Name+"</option>")
            })
        })
    }

    function loadcity() {

        var sid = $("#ddlstate").val()

        $.get('@Url.Action("GetCity", "Cascade")', { id: sid }, function (response) {

            $("#ddlcity").empty()
            $("#ddlcity").append("<option>Select</option>")

            $.each(response, function(i,e) {
                $("#ddlcity").append("<option value="+e.Id+">"+e.Name+"</option>")
            })
        })
    }
</script>

Sonal_DropDown/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Sonal_DropDown/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Sonal_DropDown/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Sonal_DropDown/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>